export const addAdminNote = `This is the Add Admin page. Here, you can add sub-Admins. This page includes fields for adding the sub-Admin's name, email ID, password, and a list of sites where you can select one or multiple sites. It also has a toggle button for blocking the sub-Admin.`;
export const editAdminNote = `This is the Edit Admin page. Here, you can Editing sub-Admins. This page includes fields for adding the sub-Admin's name, email ID, password, and a list of sites where you can select one or multiple sites. It also has a toggle button for blocking the sub-Admin.`;
export const listAdminNote = `This is the All Admin List page. There is an Add Admin button to create sub-admins. A filter dropdown is available to filter details by status, allowing you to view all admins and their sub-admins. The table includes the name of the Admin, Admin email ID, created date, updated date, status indicating whether the Admin or sub-Admin is active or inactive, the site assigned to the sub-Admin, and a Edit button to Editing specific Admin details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status of a particular sub-Admin or multiple sub-Admins. The checkbox is not available for Admins, as their status cannot be changed. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
export const addCasestudyNote = `This is the Add Case Study page. This page includes fields for adding the Case Study Title, Upload Image, long Description, short Description, Upload Pdf, and a list of sites where you can select one or multiple sites. It also has a two toggle button for Is Case Study Active? for status of Case Study Active or Inactive and Is Case Study Global? for set Case Study for all Site or for paricular Site.`;
export const editCasestudyNote = `This is the Edit Case Study page. This page includes fields for Editing the Case Study Title, long Description, Short Description, Upload Image, Upload Pdf,you can also download pdf and Image and a list of sites where you can select one or multiple sites. It also has a two toggle button for Is Case Study Active? for status of Case Study Active or Inactive and Is Case Study Global? for set Case Study for all Site or for paricular Site.`;
export const listCasestudyNote = `This is the All Case Study List page. There is an Add CaseStudy button to add a case study. A filter dropdown is available to filter details by status, allowing you to view all Case Study. The table includes the name of the Case Study Title, created date, updated date, status indicating whether the Case Study is Active or Inactive, the site assigned to the Case Study, and a Edit button to Editing specific Case Study details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status of a particular Case Study or multiple Case Study. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
export const addCategoryNote = `This is the "Add Category" page. This page includes fields for adding the category name.`;
export const editCategoryNote = `This is the "Edit Category" page. This page includes fields for editing the category name.`;
export const listCategoryNote = `This is the All Categories List page. There is an Add Catogory button to add a Categories. The table includes the name of the Categories, create date,update date and a Edit button to Editing specific Categories  details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
export const addEnquiryNote = `This is the Enquiry Details page. Here, you can find the details of a particular enquiry. This page includes the customer's name, email, mobile number, message, service, and subject. It also displays the request header of the specific website, the user agent string to identify the browser, version, and operating system of the client's device to web servers, the customer's IP address, the website name for that enquiry, and the date and time when the enquiry was created.`;

export const listEnquiryNote = `This is All Enquiries Page. Here, you can view all enquiries from all websites. The table includes the customer's name who created the enquiry, their email, mobile number, enquiry service, subject, message, website associated with the enquiry, the created date, the updated date, and a view button to display specific customer enquiry details. There is a site dropdown that lists all website names selecting a specific website will show only the details related to that website in the table. Additionally, In the table, there is a checkbox for deleting a particular enquiry or multiple enquiries.`;

export const addGuideNote = `This is the Add Guide page. This page includes fields for adding the Guide Title, Description, Upload Image, Upload Pdf, and a list of sites where you can select one or multiple sites. It also has a two toggle button for Is Guide Active? for status of Guide Active or Inactive and Is Guide Global? for set Guide for all Site or for paricular Site.`;
export const editGuideNote = `This is the Edit Guide page. This page includes fields for Editing the Guide Title, Description, Upload Image, Upload Pdf,you can also download pdf and Image and a list of sites where you can select one or multiple sites. It also has a two toggle button for Is Guide Active? for status of Guide Active or Inactive and Is Guide Global? for set Guide for all Site or for paricular Site.`;
export const listGuideNote = `This is the All Guides List page. There is an "Add Guide" button to add a guide. A filter dropdown is available to filter details by status, allowing you to view all guides. The table includes the name of the Guide Title, created date, updated date, status indicating whether the Guide is Active or Inactive, the site assigned to the Guide, and a Edit button to Editing specific Guide details. There is also a site dropdown that lists all website names; selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status of a particular Guide or multiple Guide. The checkbox is not available for Admins, as their status cannot be changed. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
export const addMailingNote = `This is the Mailing List Details page. Here, you can find the details of a particular Mail Detials. This page includes the customer's email. It also displays the request header of the specific website, the user agent string to identify the browser, version, and operating system of the client's device to web servers, the customer's IP address, the website name for that enquiry, and the date and time when the enquiry was created.`;

export const listMailingNote = `This is the Mailing Page. Here, you can view all Mail-ID of all Customer. The table includes the customer's Mail-ID who created the enquiry, website associated with the enquiry, the created date, the updated date, and a view button to display specific Email details. There is a site dropdown that lists all website names selecting a specific website will show only the details related to that website in the table. Additionally, In the table, there is a checkbox for deleting a particular enquiry or multiple Mailing. There is a search dropdown, and when you select an option, you can search the table based on the selected option. `;

export const addPopupNote = `This is the Add Popup page. This page includes fields for adding the popup name, a position dropdown where you can set the popup's position, and the "After Page Load (in seconds)" field, which indicates how many seconds after the page loads the popup will appear. The "At Page Scroll (in percent)" field allows you to set the percentage of the page scroll at which the popup will appear. The "Again When Canceled" field specifies how many seconds after the popup is closed it will reappear. The "Device Type" dropdown allows you to select the device-specific popup. The "Publish Date" determines when the popup will start showing, while the "Archive Date" sets when the popup will stop showing on the website.

The "Content Type" dropdown has several options. The first option is "Basic," which shows a title, image upload, and a settings list. The settings list includes:

"On Page Load": Displays basic content when the page loads.
"On Page Unload": Displays the popup content before the page unloads.
"Off Once Submitted": Closes the popup when the user clicks a button, preventing it from showing again.
The second option for "Content Type" is "Guide," which offers two additional settings: "All Global Guides" (content from all guides) and "All Site Guides" (content from guides on all sites). It also includes an "Additional Guides" list for specific popup content. The same options apply to the "Case Study" content type.

The "Select Site" dropdown allows you to select a particular site. Additionally, there are two toggle buttons: one for "Is Popup Active?" to set the status of the popup as active or inactive.`;
export const editPopupNote = `This is the "Add Popup" page. This page includes fields for adding the popup name, a position dropdown where you can set the popup's position, and the "After Page Load (in seconds)" field, which indicates how many seconds after the page loads the popup will appear. The "At Page Scroll (in percent)" field allows you to set the percentage of the page scroll at which the popup will appear. The "Again When Canceled" field specifies how many seconds after the popup is closed it will reappear. The "Device Type" dropdown allows you to select the device-specific popup. The "Publish Date" determines when the popup will start showing, while the "Archive Date" sets when the popup will stop showing on the website.

The "Content Type" dropdown has several options. The first option is "Basic," which shows a title, image upload, and a settings list. The settings list includes:

"On Page Load": Displays basic content when the page loads.
"On Page Unload": Displays the popup content before the page unloads.
"Off Once Submitted": Closes the popup when the user clicks a button, preventing it from showing again.
The second option for "Content Type" is "Guide," which offers two additional settings: "All Global Guides" (content from all guides) and "All Site Guides" (content from guides on all sites). It also includes an "Additional Guides" list for specific popup content. The same options apply to the "Case Study" content type.

The "Select Site" dropdown allows you to select a particular site. Additionally, there are two toggle buttons: one for "Is Popup Active?" to set the status of the popup as active or inactive.`;
export const listPopupNote = `This is the All Popups List page. There is an Add Popups button to add a Popups. A filter dropdown is available to filter details by status, allowing you to view all Popups. The table includes the name of the Popups, Device type, type for content type, status indicating whether the Popups  is Active or Inactive, created date, updated date, the site assigned to the Popups, and a Edit button to Editing specific Popups  details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status, create dupitcate Popups and delete of a particular Popups or multiple Popups. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;

export const addWebsiteNote = `This is the Add Website page. It includes fields for adding the Website Name and Host. There is a "Forward Email" toggle, which, when switched on, displays a field for entering an email address. After entering an email and clicking the "Add Email" button, the email is added to a list. You can also remove emails from this list. The SMTP dropdown displays all available SMTP options, which can be selected for sending emails. The Webhook field facilitates two-way communication between tools, apps, and programs used by the organization whenever new data is available for the website. Additionally, there are toggle buttons, including one labeled "Is Website Active?" to set the status of the site as active or inactive.`;
export const editWebsiteNote = `This is the "Edit Website" page. It includes fields for ediing the Website Name and Host. There is a "Forward Email" toggle, which, when switched on, displays a field for entering an email address. After entering an email and clicking the "Add Email" button, the email is added to a list. You can also remove emails from this list. The SMTP dropdown displays all available SMTP options, which can be selected for sending emails. The Webhook field facilitates two-way communication between tools, apps, and programs used by the organization whenever new data is available for the website. Additionally, there are toggle buttons, including one labeled "Is Website Active?" to set the status of the site as active or inactive.`;
export const listWebsiteNote = `This is the All Websites List page. There is an Add Website button to add a Websites. A filter dropdown is available to filter details by status, allowing you to view all Websites. The table includes the keys of the website,Webiste name, web address, create date, update date, status indicating whether the Websites  is Active or Inactive, and a Edit button to Editing specific Websites  details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status of a particular Websites or multiple Websites. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;

export const addSMTPNote = `This is the Add STMP page. This page includes fields for adding the STMP title, host, Port, and a Select Type dropdown where you can select Security Protocol, User, and Password for the STMP.`;
export const editSMTPNote = `This is the Edit STMP page. This page includes fields for editing the STMP title, host, Port, and a Select Type dropdown where you can select Security Protocol, User, and Update Password for the STMP.`;
export const listSMTPNote = `This is the All SMTP List page. There is an Add CaseStudy button to add a SMTP. The table includes the name of the SMTP, Host, the site assigned to the SMTP, and a Edit button to Editing specific SMTP details. Additionally, There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
export const addTestimonialNote = `This is the Add Testimonials page. This page includes fields for adding the testimonial title, uploading an image, a short description, uploading a PDF, and a Select Type dropdown where you can upload an image, video, or text for the testimonial. It also includes a list of sites and category where you can select one or multiple sites. Additionally, there are two toggle buttons one for Is Testimonial Active? to set the status as active or inactive, and another for Is Testimonial Global? to determine if the testimonial applies to all sites or a particular site.`;
export const editTestimonialNote = `This is the Edit Testimonials page. This page includes fields for Editing the testimonial title, uploading an image, a short description, uploading a PDF, and a Select Type dropdown where you can upload an image, video, or text for the testimonial Their is also download option of image and video. It also includes a list of sites and category where you can select one or multiple sites. Additionally, there are two toggle buttons one for Is Testimonial Active? to set the status as active or inactive, and another for Is Testimonial Global? to determine if the testimonial applies to all sites or a particular site.`;
export const listTestimonialNote = `This is the All Testimonials List page. There is an Add CaseStudy button to add a Testimonials. A filter dropdown is available to filter details by status, allowing you to view all Testimonials. The table includes the name of the Testimonials, status indicating whether the Testimonials  is Active or Inactive, the site assigned to the Testimonials, and a Edit button to Editing specific Testimonials  details. There is also a site dropdown that lists all website names. selecting a specific website will show only the details related to that website in the table. Additionally, the table has a checkbox for changing the status of a particular Testimonials or multiple Testimonials. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
