export const addPopupNote = `This is the Add Popup page. This page includes fields for adding the popup name, a position dropdown where you can set the popup's position, and the "After Page Load (in seconds)" field, which indicates how many seconds after the page loads the popup will appear. The "At Page Scroll (in percent)" field allows you to set the percentage of the page scroll at which the popup will appear. The "Again When Canceled" field specifies how many seconds after the popup is closed it will reappear. The "Device Type" dropdown allows you to select the device-specific popup. The "Publish Date" determines when the popup will start showing, while the "Archive Date" sets when the popup will stop showing on the site.
The "Content Type" dropdown has several options. The first option is "Basic," which shows a title, image upload, and a settings list. The settings list includes:
"On Page Load": Displays basic content when the page loads.
"On Page Unload": Displays the popup content before the page unloads.
"Off Once Submitted": Closes the popup when the user clicks a button, preventing it from showing again.
The second option for "Content Type" is "Guide," which offers two additional settings: "All Global Guides" (content from all guides) and "All Site Guides" (content from guides on all sites). It also includes an "Additional Guides" list for specific popup content. The same options apply to the "Case Study" content type.
The "Select Site" dropdown allows you to select a particular site. Additionally, there are two toggle buttons: one for "Is Popup Active?" to set the status of the popup as active or inactive.`;

export const editPopupNote = `This is the "Edit Popup" page. This page includes fields for editing the popup name, a position dropdown where you can update the popup's position, and the "After Page Load (in seconds)" field, which indicates how many seconds after the page loads the popup will appear. The "At Page Scroll (in percent)" field allows you to set the percentage of the page scroll at which the popup will appear. The "Again When Canceled" field specifies how many seconds after the popup is closed it will reappear. The "Device Type" dropdown allows you to select or change the device-specific popup. The "Publish Date" determines when the popup will start showing, while the "Archive Date" sets when the popup will stop showing on the site. 
The "Content Type" dropdown has several options. The first option is "Basic," which shows a title, image upload, and a settings list. The settings list includes:
"On Page Load": Displays basic content when the page loads.
"On Page Unload": Displays the popup content before the page unloads.
"Off Once Submitted": Closes the popup when the user clicks a button, preventing it from showing again.
The second option for "Content Type" is "Guide," which offers two additional settings: "All Global Guides" (content from all guides) and "All Site Guides" (content from guides on all sites). It also includes an "Additional Guides" list for specific popup content. The same options apply to the "Case Study" content type. 
The "Select Site" dropdown allows you to select or update a particular site. Additionally, there are two toggle buttons: one for "Is Popup Active?" to set the status of the popup as active or inactive.`;

export const listPopupNote = `This is the All Popups List page. There is an Add Popups button to add a Popups. A filter dropdown is available to filter details by status, allowing you to view all Popups. The table includes the name of the Popups, Device type, type for content type, status indicating whether the Popups  is Active or Inactive, created date, updated date, the site assigned to the Popups, and a Edit button to Editing specific Popups  details. There is also a site dropdown that lists all site names. selecting a specific site will show only the details related to that site in the table. Additionally, the table has a checkbox for changing the status, create duplicate Popups and delete of a particular Popups or multiple Popups. There is a search dropdown, and when you select an option, you can search the table based on the selected option.`;
